In [ ]:
import numpy as np
import random

#Ejercicio 1: Crear un array de 10 elementos con ceros.

# np.full crea un array con el mismo valor n veces
a = np.full(10, 0)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Ejercicio 2: Genera un array con los números del 1 al 20.

#np.arange crea un array en un rango de valores en una secuencia
a = np.arange(1, 21, 1)
a


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
#Ejercicio 3: Crea un array con los números pares del 2 al 50.
a = np.arange(2, 51, 2)
a


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50])

In [ ]:
#Ejercicio 4: Genera un array de tamaño 8 donde todos los valores sean 7.
a = np.full(8, 7)
a


array([7, 7, 7, 7, 7, 7, 7, 7])

In [ ]:
#Ejercicio 5: Crea una matriz de 4x4 con valores aleatorios entre 0 y 1.

#np.random.default_rng(): numeros aleatorios
#rng.random((4,4)): matriz de dimensiones x, y
#por default vienen valores entre 0 y 1

rng = np.random.default_rng()
a = rng.random((4,4))
a

array([[0.91814448, 0.55244767, 0.00264473, 0.17428153],
       [0.7274695 , 0.99411711, 0.59865159, 0.40531396],
       [0.58521207, 0.64535153, 0.50069536, 0.2894292 ],
       [0.34745084, 0.16958785, 0.50911087, 0.35478263]])

In [ ]:
#Ejercicio 6: Realiza la suma elemento a elemento de los arrays a=[1,2,3], b=[4,5,6].

#Creamos 2 array con los valores determinados
a = np.array([1,2,3])
b = np.array([4,5,6])

#Luego se suman
a + b

array([5, 7, 9])

In [ ]:
#Ejercicio 7: Multiplica dos matrices 3x3 de enteros aleatorios entre 1 y 10.

#np.random.randint(): genera numeros aleatorios entre 1 y 11 (sin tomar el 11), en una matriz de 3x3
a = np.random.randint(1, 11, size=(3, 3))
b = np.random.randint(1, 11, size=(3, 3))


print(a)
print("\n") #Bajar un renglon
print(b)
print("\n") #Bajar un renglon
print(a * b)

[[9 2 7]
 [3 7 1]
 [1 2 3]]


[[9 7 1]
 [7 7 1]
 [5 3 6]]


[[81 14  7]
 [21 49  1]
 [ 5  6 18]]


In [ ]:
#Ejercicio 8: Crea un array de 15 valores aleatorios entre 1 y 100 e imprime su máximo, mínimo y promedio.

a = np.random.randint(1, 101, size=15)
print(a)
print("\n") #Bajar un renglon
print("El maximo es: ", a.max()) #a.max valor maximo
print("El mínimo es: ", a.min()) #a.min valor minimo
print("El promedio es de: ", a.mean()) #a.mean valor promedio

[39 70 95  2 95 83 12 32  5 29  7 45 10 72 48]


El maximo es:  95
El minimo es:  2
El promedio es de:  42.93333333333333


In [ ]:
#Ejercicio 9: Genera una matriz 5x5 con valores del 1 al 25 y extrae su diagonal.

# .reshape hace que la matriz de 25 valores se distribuyan entre los espacios de la matriz de 5 x 5
x = np.arange(1, 26).reshape(5, 5)

# np.diag extrae los valores de la diagonal de la matriz "x"
diagonal = np.diag(x)
print(x)

print("\n") #Bajar un renglon
print(diagonal)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


[ 1  7 13 19 25]


In [ ]:
#Ejercicio 10: Dada una matriz 5x5 de enteros aleatorios entre 1 y 20, calcula la suma de cada fila y columna.

a = np.random.randint(1, 21, size=(5, 5))
print(a)
print("\n") #Bajar un renglon
print(a.sum(axis=0))
print("\n") #Bajar un renglon
print(a.sum(axis=1))


[[15 18 18  1 15]
 [ 8  2  6 20  4]
 [19  5 19 15  6]
 [20 18 16 20  8]
 [10  3  4 16 16]]


[72 46 63 72 49]


[67 40 64 82 49]
